---
- name: Get 1Password info from localhost
  hosts: localhost
  roles:
    - ohmyzsh
    - backup_info

- name: Push latest backup file from localhost to all remote hosts  # noqa syntax-check[specific]
  # All remote hosts except localhost and its resolved hostname
  hosts: all:!localhost:!{{ hostvars['localhost'].ansible_hostname.lower() }}
  roles:
    - backup_info
    - export
